### ISSUE TITLE
Compilation with Compute Capability below default succeeds but program crashes miserably

### ISSUE THREAD

**Issue by mhantke** [FilipeMaia/libspimage#8]
Throws following error in tests or when starting phasing with CUDA support:
--
CUDA error: "Invalid Device function" at phasing.cu:90
--
Fix: Set CUDA_NVCC_FLAGS in advanced cmake compilation options to -arch=sm_11 (or the computing capability version that the card supports).

It would be nicer if that was done automatically.

Problematic is also that low computing capability won't be supported for much longer by Thrust and CUDA...

**Comment by FilipeMaia** [comment]
Commit c7e87814 causes the program to always crash with the above error.
