### ISSUE TITLE
order of image center coordinates

### ISSUE THREAD

**Issue by mhantke** [FilipeMaia/libspimage#9]
The order of center coordinates is not in line with the order how image matrices are built (x=fastest changing dimension). This is confusing.

image_util.c:
  res->detector->image_center[0] = (x-1)/2.0;
  res->detector->image_center[1] = (y-1)/2.0;
  res->detector->image_center[2] = (z-1)/2.0;

**Comment by mhantke** [comment]
Same here in these center of mass functions:

linear_alg.c:371-501
sp_3matrix_center_of_mass
sp_i3matrix_center_of_mass
sp_i3matrix_binary_center_of_mass
sp_i3matrix_binary_center_of_mass_shifted

**Comment by mhantke** [comment]
Same problem with pixel_size...

**Comment by ekeberg** [comment]
I think this is different from fast or slow varying indices. This should follow our standard for how to order x, y and z. Function variables in libspimage always use the x, y, z order and I see no problem in using the same order internally. This also makes python wrapper behavior, where these internal variables are more often used externally, more consistent with function calls. What I think is confusing is that our ordering of x, y, z in function calls is not the same as how indexing works for example in python.

**Comment by mhantke** [comment]
Agreed. But isn't that de facto the same?

**Comment by mhantke** [comment]
We agree on keeping the following conventions:
- pixel value = image[z,y,x]
- function(x,y,z)
- vector = [v_x,v_y,v_z]
